# Dataframe
-----------

Dataframe is most commonly used object in pandas. It is a table like datastructure containing rows and columns similar to excel spreadsheet

In [1]:
# Define the data

weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']
}


print(weather_data, type(weather_data))

{'day': ['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], 'temperature': [32, 35, 28, 24, 32, 31], 'windspeed': [6, 7, 2, 7, 4, 2], 'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']} <class 'dict'>

In [2]:
# Create DataFrame
import pandas as pd

df = pd.DataFrame(weather_data)

print(type(df))

print('-----------------------------------------------------')

df

<class 'pandas.core.frame.DataFrame'>
-----------------------------------------------------

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [3]:
# DataFrame values to CSV file(Comma seperated file)

df.to_csv('weather_data.csv', index=False)

print("CSV file created successfully.")

CSV file created successfully.

In [4]:
# Open CSV file

sampleFile = pd.read_csv("weather_data.csv")

sampleFile

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
# To Find the shape of given csv file
# rows, columns = df.shape

df.shape

(6, 4)