# Read Csv File

In [1]:
import pandas as pd

In [2]:
# Open CSV file

df = pd.read_csv("weather_data.csv")

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

# Get Row values

In [3]:
print(df.head())  # Displays the first 5 rows

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [4]:
print(df.head(2))  # Displays the first 5 rows

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [5]:
df.tail()  # Displays the last 5 rows

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [6]:
df.tail(2)  # Displays the last 5 rows

        day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

# Get Column values

In [8]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [10]:
dayValues = df['day'] # or df.day

dayValues

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [11]:
df[['day','temperature']]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

# Operations On DataFrame or csv or xlsx Files

In [12]:
print(df['temperature'].max())

35

In [14]:
df[df['temperature'] > 31]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [15]:
[df['temperature'] == df['temperature'].max()]

[0    False
 1     True
 2    False
 3    False
 4    False
 5    False
 Name: temperature, dtype: bool]

In [20]:
df['day'][df['temperature'] == df['temperature'].max()]

1    1/2/2017
Name: day, dtype: object

In [19]:
df[['day', 'temperature']][df['temperature'] == df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [21]:
df[df['temperature'] == df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny