# Create CSV Files

In [1]:
import pandas as pd

In [2]:
# Define the data

weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']
}


print(weather_data, type(weather_data))

{'day': ['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], 'temperature': [32, 35, 28, 24, 32, 31], 'windspeed': [6, 7, 2, 7, 4, 2], 'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']} <class 'dict'>

In [3]:
# Create DataFrame

df = pd.DataFrame(weather_data)

print('-----------------------------------------------------')

df

-----------------------------------------------------

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [4]:
# DataFrame values to CSV file(Comma seperated file)

df.to_csv('weather_data.csv', index=False)

print("CSV file created successfully.")

CSV file created successfully.

# Create Microsoft Excel File
# Write two dataframes to two separate sheets in excel

In [5]:
# Create df_stocks, df_weather DataFrame

df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [6]:
df_stocks

  tickers  price     pe    eps
0   GOOGL    845  30.37  27.82
1     WMT     65  14.26   4.61
2    MSFT     64  30.97   2.12

In [7]:
df_weather

        day  temperature  event
0  1/1/2017           32   Rain
1  1/2/2017           35  Sunny
2  1/3/2017           28   Snow

# Create Excel File

If have a No module error (openpyxl) then run command in Command Prompt(CMD)

pip install openpyxl

In [8]:
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks") 
    df_weather.to_excel(writer, sheet_name="weather")

print('Excel File Created Successfully!')

Excel File Created Successfully!

# Read Csv File:

In [9]:
df = pd.read_csv("weather_data.csv")

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

# Read Excel File

In [10]:
# stock_data.xlsx File import on directory. then run the command

# Read Excel file for stocks Sheet

df = pd.read_excel("stocks_weather.xlsx","stocks")

df

   Unnamed: 0 tickers  price     pe    eps
0           0   GOOGL    845  30.37  27.82
1           1     WMT     65  14.26   4.61
2           2    MSFT     64  30.97   2.12

In [11]:
# Read Excel file for weather Sheet

df = pd.read_excel("stocks_weather.xlsx","weather")

df

   Unnamed: 0       day  temperature  event
0           0  1/1/2017           32   Rain
1           1  1/2/2017           35  Sunny
2           2  1/3/2017           28   Snow